pipeline/test_extract.py

Allows workflows to run in the pipeline folder.
Closes #7

First (passing) test

---

.gitignore
pipeline/extract.py
pipeline/requirements.txt

I improved the readability and reusability of the script, adding environmental variables for links.

improved extract script for reusability

---

pipeline/extract.py

added the extraction of pdf urls and combining them with title in a list of dictionaries

added pdf extraction functionality

---

database/schema.sql

database schema

---

pipeline/extract.py

A main function (extract_cases) to be used in the transform script.
Closes #39

Extract main func

---

.gitignore
database/schema.sql
database/seeds.sql
judges/pipeline.ipynb
judges/pipeline.py

cleaned function names + put functions in main()

Judge scrape

---

.gitignore
pipeline/requirements.txt
pipeline/transform.py

- added transform script
- incorporate use of GPT-API
- get summary of introduction
- get verdict in one word from conclusion/last page
closes #31 
closes #16

first push for transform script

---

judges/pipeline.py
pipeline/load.py

- added loading script for cases and hearing dates
- first draft, not been tested yet on database until judges information has been uploaded.
closes #52

first push of loading script for cases and hearing dates

---

pipeline/Dockerfile
pipeline/pipeline.py

Added the scripts for dockerising and the lambda version of our etl pipeline.
closes #60, #61

dockerised and lambdarised etl

---

database/schema.sql

Want to store date and case title so updated schema. Other minor edits.
Closes #69

reworked ERD so update schema

---

pipeline/extract.py

Improved date and case_no regexes.
Closes #50

Improve regex

---

pipeline/load.py
pipeline/transform.py
terraform/pipeline/main.tf
terraform/pipeline/pipeline.tf
terraform/pipeline/variables.tf

- ETL required updating to conform to new ERD approach.
- Terraformed ETL script successfully, new updates can be added by updating docker image on ECR repo.
closes #73

add terraform script for etl and update etl

---

pipeline/extract.py
pipeline/requirements.txt
pipeline/test_extract.py

Added some real tests to extract.
Closes #37

Extract tests

---

pipeline/extract.py

Pulled out repetitive code into a separate function called 'get_case_soup'.
Closes #67

Refactor extract

---

database/insert_schema.sh
database/schema.sql
database/seed.sh
database/seeds.sql

Fixed the issue with the case not being available, and then sorted out the all the bash scripts aswell

fixed sql bugs and schema

---

database/delete.sh
database/seeds.sql

Added sample data so we can test our pipeline and see if it works

added seeded judge sample data

---

pipeline/extract.py
pipeline/requirements.txt

Added functions that talk to the db and pull out the titles we already have stored - prevents us from adding duplicate cases to the db.
Closes #70

Title cache

---

database/schema.sql
database/seeds.sql
pipeline/load.py
pipeline/transform.py

- updated bug with transform and load script where datetime was in incorrect format.
closes #91

update transform, load and schema

---

pipeline/extract.py

Apologies for not catching this sooner. Whenever you call extract_cases() make sure you check for None first before you continue with your code.
Extract cases will now return 'None' if there are no new cases to be processed and added to the database.
Closes #99

Extract bug

---

README.md

Update README.md to add new information

---

pipeline/test_extract.py
pipeline/transform.py

Adding more tests for extract.py - specifically when dealing with Beautiful Soup.
Closes #87 
Closes #9
Closes #107

Beautiful soup tests

---

pipeline/load.py

- updated the sql query that matched judge name from database to that of which parsed from pdf
- made it to take 'ILIKE' so it is case insensitive.
closes #111

update load to get like judge names

---

database/seeds.sql

- added N/A ID columns for judge_type, circuit and judge tables

improved schema for unknowns

---

judges/requirements.txt
judges/test_pipeline.py

Added tests for judge pipeline. I did test things like loading to the database or the actual scraping itself, since this relies on external sources.
Closes #112

Test judge pipeline

---

dashboard/dashboard.py
dashboard/requirements.txt

Dashboard skeleton

---

pipeline/extract.py

Checks database to see if case_no has already been stored - discards the case if so.
closes #145

Extract case no

---

pipeline/extract.py

We changed our minds about how to approach duplicate case_no_ids -> we're no longer using this as a primary key.
Therefore, we no longer need to check whether a case number already exists in the database.
Only thing changed is the date regex.
Closes #154

Reverted most of the changes made

---

api/app.py
api/dockerfile
api/queries.py
api/templates/homepage.html

This PR adds query paramters to the api endpoints `/cases` and `/judges`.
Closes #148 
Closes #149 
Closes #142

Api filters

---

dashboard/dashboard.py

done dashboard judge profile script

---

dashboard/.streamlit/config.toml
dashboard/streamlit_app.py

added toml; renamed dashboard.py to streamlit_app.py

---

dashboard/Dockerfile

added Dockerfile

---

api/main.tf
api/variables.tf
database/schema.sql
terraform/main.tf

- terraformed the api scripts to be deployed on ecs service.
- updated the schema to accept "TEXT" for title column in "transcript" table
closes #167 
fixex #169

terraformed api and updated schema

---

pipeline/extract.py
pipeline/load.py
pipeline/pipeline.py
pipeline/transform.py

-adjusted the schema to account for more than 1 case number id
fixes #155

configured schema and updated ETL for formatting date

---

terraform/api.tf
terraform/main.tf

- merged the terraform files so that one terraform command will run the product.

combined terraform files into one

---

pipeline/extract.py
pipeline/pipeline.py
pipeline/transform.py

This now works both locally and in the cloud. The difference now is the env variables. For example, in the local .env the STORAGE_FOLDER variable should be 'data', while for the cloud version (i.e. terraformed version) the variable should be '/tmp'.
Closes #161 
Closes #175

Local v cloud

---

dashboard/layout.py
dashboard/streamlit_app.py

This PR creates a new file to organise the layout of the dashboard including a sidebar.
Closes #127

Dashboard sidebar

---

pipeline/extract.py
pipeline/transform.py

Fixed some of the regex, less cases are being dropped now.
Closes #179 
Closes #92

Name regex

---

dashboard/charts.py
dashboard/layout.py
dashboard/streamlit_app.py

This PR organises the dashboard files and adds charts to the dashboard.
closes #136 
closes #134 
closes #182

Dashboard charts

---

judges/pipeline.py

Checks if judges are already stored in the database before adding them.
Closes #186

Check judges db

---

dashboard/streamlit_app.py

done adding controls

---

README.md

Added wireframe to README and cleaned up a few bits.
Closes #202

Add wireframe to readme

---

dashboard/case_profiles.py
dashboard/streamlit_app.py

- added catching of error in connecting to database when database is down/delayed.

added catching of error when database does not connect

---

dashboard/streamlit_app.py

fixed controls

---

terraform/main.tf
terraform/variables.tf

Added terraform variables so terraforming can be done on any system.
closes #192

add variables for terraforming

---

dashboard/streamlit_app.py

passed input dict into filtered df function; moved charts into columns

---

dashboard/charts.py
dashboard/streamlit_app.py

Added judge count line graph. About to reserve merge conflicts.
Closes #132

Judge count line graph

---

dashboard/charts.py
dashboard/streamlit_app.py

This PR add a stacked bar chart to the dashboard

Stacked bar chart for verdicts

---

dashboard/charts.py
dashboard/streamlit_app.py

debugged controls and filtered

---

dashboard/charts.py

Readded return to get_case_count_line_chart

---

dashboard/case_profiles.py
dashboard/charts.py
dashboard/layout.py
dashboard/streamlit_app.py

Reorganised the dashboard in a way that makes more sense with the filters.
Added colour schemes.
Standardised some text.
Closes #232 
Closes #233
Closes #225

Reorganise dashboard

---

dashboard/charts.py

Fix dashboard bug

---

dashboard/Dockerfile

Added toml Docker image config

Added toml file

---

dashboard/charts.py
dashboard/pages/1_Charts.py
dashboard/requirements.txt
dashboard/streamlit_app.py
pipeline/extract.py
pipeline/test_extract.py

- polished dashboard (moved sections into different pages to declutter)
- side task: deleted infinity function in pipeline/extract since it's not used
closes #252

polished dashboard; deleted infinity function in pipeline/extract

---

dashboard/streamlit_app.py

closed CONN in dashboard script
closes #254

closed CONN

---

dashboard/case_profiles.py
dashboard/charts.py
dashboard/layout.py
dashboard/pages/1_Charts.py
dashboard/streamlit_app.py

- swapped chart positions
- moved verdict metrics
- cleaned inconsistent filter placeholders for searches
- removed empty result placeholder for judge search
- added count metrics

Dashboard swap add width
